title: Блог Ивана Гришаева
email: ivan@grishaev.me
description: >
  Пишу о программировании, образовании, книгах, переговорах.
baseurl: ""
url: "http://grishaev.me"
twitter_username: i_grishaev
github_username: igrishaev
author: Иван Гришаев
paginate: 10
markdown: kramdown
gems:
  - kramdown
  - rouge
  - jekyll-watch
  - redcarpet
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
redcarpet:
  extensions:
    - autolink
host: 0.0.0.0
port: 4000
