title: "Ivan Grishaev's blog"
email: ivan@grishaev.me
description: >
  Writing on programming, education, books and negotiations.
baseurl: ""
url: "http://grishaev.me"
twitter_username: i_grishaev
github_username: igrishaev
author: Ivan Grishaev
paginate: 10
markdown: kramdown
gems:
  - kramdown
  - rouge
  - jekyll-watch
  - redcarpet
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
redcarpet:
  extensions:
    - autolink
host: 0.0.0.0
port: 4000
