title: "Ivan Grishaev's blog"
email: ivan@grishaev.me
description: >
  Writing on programming, education, books and negotiations.
baseurl: ""
lang: ru
url: "http://grishaev.me"
twitter_username: i_grishaev
github_username: igrishaev
author: Ivan Grishaev
paginate: 10
markdown: kramdown
plugins:
  - kramdown
  - rouge
  - jekyll-watch
  - redcarpet
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll/tagging

exclude:
  - gh-pages
  - instantview
  - scripts
  - todo.org
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile

redcarpet:
  extensions:
    - autolink

host: 0.0.0.0
port: 4000

tag_page_layout: tag_page
tag_page_dir: tag

tag_permalink_style: pretty
