title: "Ivan Grishaev's blog"
email: ivan@grishaev.me
description: >
  Writing on programming, education, books and negotiations.
baseurl: ""
lang: ru
url: "https://grishaev.me"

url_github: "https://github.com/igrishaev"
url_telegram: "tg://resolve?domain=igrishaev_blog"
url_linkedin: "https://www.linkedin.com/in/igrishaev"

url_gumroad_clj_prod_ru: "https://gum.co/clojure-in-prod"
url_s3_static: "https://s3.amazonaws.com/igrishaev.public"

author: Ivan Grishaev
paginate: 10
markdown: kramdown

future: true

plugins:
  - kramdown
  - rouge
  - jekyll-watch
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll/tagging
  - jekyll-sitemap
  - stringex

exclude:
  - aws
  - gh-pages
  - instantview
  - scripts
  - todo.org
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - Makefile

host: 0.0.0.0
port: 4000

tag_page_layout: tag_page
tag_page_dir: tag

tag_permalink_style: pretty

kramdown:
  auto_ids: true
  auto_id_stripping: true
  transliterated_header_ids: true
