title: Блог Ивана Гришаева
email: ivan@grishaev.me
description: >
  Пишу о программировании, образовании, книгах, переговорах.
baseurl: ""
url: "http://grishaev.me"
twitter_username: i_grishaev
github_username: igrishaev

paginate: 10

markdown: redcarpet
gems:
  - kramdown
  - rouge
  - jekyll-watch
  - redcarpet
  - jekyll-paginate
  - jekyll-redirect-from

redcarpet:
  extensions:
    - autolink
